apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroomapp-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: classroomapp
  template:
    metadata:
      labels:
        app: classroomapp
    spec:
      containers:
        - name: tetris
          image: aashiqq/classroomapp:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: classroomapp-svc
spec:
  selector:
    app: classroomapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
